---
- name: "Tester les agents GLPI installés"
  hosts: all
  become: yes

  tasks:
    - name: "1. Vérifier le service"
      ansible.builtin.systemd:
        name: glpi-agent
        state: started
        enabled: yes

    - name: "2. Vérifier la configuration"
      ansible.builtin.command: cat /etc/glpi-agent/agent.cfg
      register: config_content

    - name: "3. Afficher la configuration"
      ansible.builtin.debug:
        msg: |
          Configuration sur {{ inventory_hostname }}:
          {{ config_content.stdout }}

    - name: "4. Tester l'envoi d'inventaire"
      ansible.builtin.shell: |
        timeout 10 glpi-agent --inventory --debug 2>&1 | tail -5
      register: inventory_test
      ignore_errors: yes
      changed_when: false

    - name: "5. Afficher le résultat du test"
      ansible.builtin.debug:
        msg: |
          Test inventaire {{ inventory_hostname }}:
          {{ inventory_test.stdout }}

    - name: "6. Vérifier les logs du service"
      ansible.builtin.shell: |
        journalctl -u glpi-agent --no-pager -n 5
      register: service_logs
      changed_when: false

    - name: "7. Afficher les logs"
      ansible.builtin.debug:
        msg: |
          Logs GLPI Agent sur {{ inventory_hostname }}:
          {{ service_logs.stdout }}
