- name: install mariadb server package (AlmaLinux)
  tags: almalinux,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: install mariadb server
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
